services:
  postgres:
    image: postgres:15.4
    ports:
      - ${PORT:-65432}:5432
    environment:
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - PSQL_HISTORY=/var/lib/postgresql/history/postgres
    volumes:
      - ./data/postgres-data:/var/lib/postgresql/data
      - ./data/postgres-psql-history:/var/lib/postgresql/history
